---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: $MY_CLUSTER_NAME
  region: $MY_REGION
  version: $MY_VERSION
# traits of worker nodes
nodeGroups:
  - name: $MY_CLUSTER_NAME-workers
    instanceType: t3.medium
    desiredCapacity: 4
    minSize: 1
    maxSize: 4
    iam:
      # polices added to worker node role
      withAddonPolicies:
        # allows read/write to zones in Route53
        externalDNS: true
        # access to ACM
        certManager: true
